title: Course template
author: Jan Kirenz
logo: logo.png

execute:
  execute_notebooks: 'off' # cache or force

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
   - _bibliography/references.bib

repository:
  url: https://github.com/kirenz/course-template
  branch: main

html:
  use_issues_button: true
  use_repository_button: true

sphinx:
  config:
    bibtex_reference_style: author_year
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js

# Colab
launch_buttons:
  colab_url: "https://colab.research.google.com"
  binderhub_url: ""